// <auto-generated />
using System;
using AccessManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessManagerDbContext))]
    [Migration("20260427211202_ServerCreditsAndClientFinance")]
    partial class ServerCreditsAndClientFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AccessManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DiaPagamentoPreferido")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CompetenciaReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimentoFinanceiro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StatusFinanceiro")
                        .HasColumnType("int");

                    b.Property<Guid?>("TelaClienteId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TelaClienteId");

                    b.ToTable("lancamentos_financeiros", (string)null);
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.RenovacaoTelaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimentoTecnicoAnterior")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NovaDataVencimentoTecnico")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ServidorAnteriorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ServidorNovoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TelaClienteId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ValorAcordadoAnterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorAcordadoNovo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServidorAnteriorId");

                    b.HasIndex("ServidorNovoId");

                    b.HasIndex("TelaClienteId");

                    b.ToTable("renovacoes_telas_historico", (string)null);
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.Servidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("QuantidadeCreditos")
                        .HasColumnType("int");

                    b.Property<string>("SenhaPainel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioPainel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorCustoCredito")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("servidores", (string)null);
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.TelaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppUtilizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ChaveSecundaria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVencimentoTecnico")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MacOuIdApp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MarcaTv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeIdentificacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SenhaTela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ServidorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioTela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorAcordado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServidorId");

                    b.ToTable("telas_clientes", (string)null);
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.HasOne("AccessManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("LancamentosFinanceiros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessManager.Domain.Entities.TelaCliente", "TelaCliente")
                        .WithMany("LancamentosFinanceiros")
                        .HasForeignKey("TelaClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("TelaCliente");
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.RenovacaoTelaHistorico", b =>
                {
                    b.HasOne("AccessManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessManager.Domain.Entities.Servidor", "ServidorAnterior")
                        .WithMany()
                        .HasForeignKey("ServidorAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessManager.Domain.Entities.Servidor", "ServidorNovo")
                        .WithMany()
                        .HasForeignKey("ServidorNovoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessManager.Domain.Entities.TelaCliente", "TelaCliente")
                        .WithMany("RenovacoesHistorico")
                        .HasForeignKey("TelaClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ServidorAnterior");

                    b.Navigation("ServidorNovo");

                    b.Navigation("TelaCliente");
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.TelaCliente", b =>
                {
                    b.HasOne("AccessManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Telas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessManager.Domain.Entities.Servidor", "Servidor")
                        .WithMany("Telas")
                        .HasForeignKey("ServidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("LancamentosFinanceiros");

                    b.Navigation("Telas");
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.Servidor", b =>
                {
                    b.Navigation("Telas");
                });

            modelBuilder.Entity("AccessManager.Domain.Entities.TelaCliente", b =>
                {
                    b.Navigation("LancamentosFinanceiros");

                    b.Navigation("RenovacoesHistorico");
                });
#pragma warning restore 612, 618
        }
    }
}
